---
version: "2.1"
services:
  unifi_controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi_controller
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - ./data:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 5514:5514/udp
    restart: unless-stopped
